---
- name: Apply common configuration
  hosts: all
  become: yes
  roles:
    - common

- name: Install kubadm on cluster nodes
  hosts: kubernetes
  become: yes
  roles:
    - kubepackages
    - kernelopts

- name: Install haproxy on loadbalancer nodes
  hosts: loadbalancers
  become: yes
  roles:
    - haproxy

- name: Configure kubernetes cluster
  hosts: kubernetes
  become: yes
  roles:
    - kubernetes
