---
- name: Apply common configuration
  hosts: all
  become: yes
  roles:
    - common

- name: Install kubadm on cluster nodes
  hosts: kubernetes
  become: yes
  roles:
    - kubeadm

- name: Install haproxy on loadbalancer nodes
  hosts: loadbalancers
  become: yes
  roles:
    - haproxy

# - name: Configure kubernetes master nodes
#   hosts: masters
#   become: yes
#   roles:
#     - kubernetes-master
#
# - name: Configure kubernetes worker node
#   hosts: workers
#   become: yes
#   roles:
#     - kubernetes-worker
