---
- name: Check if kubeadm has already run
  stat:
    path: "/var/lib/kubelet/config.yaml"
  register: kubeadm_already_run

- name: Create kubeadm configuration file
  template:
    src: kubeadm-config.yaml.j2
    dest: /root/kubeadm-config.yaml
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname == groups['masters'][0]
  register: kubeadm_config

- name: Reset kubernetes cluster
  command: kubeadm reset -f
  when: inventory_hostname == groups['masters'][0] and kubeadm_config.changed
  register: kubeadm_reset

- name: Drop flannel conenction
  net_interface:
    name: flannel.1
    state: absent
  when: inventory_hostname == groups['masters'][0] and kubeadm_config.changed

- name: Init kubernetes master node
  command: kubeadm init --config=/root/kubeadm-config.yaml
  when: inventory_hostname == groups['masters'][0] and not kubeadm_already_run.stat.exists and kubeadm_config.changed
  register: kubeadm_init

- name: Apply flannel
  command: |
    kubectl \
      --kubeconfig=/etc/kubernetes/admin.conf \
      apply -f \
      https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
  when: inventory_hostname == groups['masters'][0]
